### ISSUE TITLE
Fix message

### ISSUE THREAD

**Issue by lalongooo** [krescruz/permuta-sep#2]
While trying to use for second time the token for password reset, this message appears:

![image](https://cloud.githubusercontent.com/assets/1671260/8049475/5c21d3ee-0e25-11e5-9c94-29883dd17b9f.png)

I think it should say something like:
* "La URL ha caducado"
* "Inicia de nuevo tu proceso de restauración de contraseña"

**Comment by krescruz** [comment]
Fixed message in template. fd04d93a78a71353578ecdc0c81ca295d6749070

**Comment by lalongooo** [comment]
Thanks!
