### ISSUE TITLE
Fix email body and subject

### ISSUE THREAD

**Issue by lalongooo** [krescruz/permuta-sep#3]
Text marked in red should display **Permutas SEP** instead of the current displayed text.

This could cause confusion, so...please update.

![image](https://cloud.githubusercontent.com/assets/1671260/8188874/25004cca-141e-11e5-992a-d1b230aecb27.png)

**Comment by krescruz** [comment]
Fix 394a5b17a6e19bc34a9bbfc5b9cfc98c5a6ded10

**Comment by lalongooo** [comment]
Thanks!
