### ISSUE TITLE
Retrieve the user email as a query string parameter

### ISSUE THREAD

**Issue by lalongooo** [krescruz/permuta-sep#4]
Could you please include the users' email as a query string parameter in the URL for password reset?

I need to do the "login" after the password reset is complete.

I could save the email captured before but this is like a non-best practice.

![image](https://cloud.githubusercontent.com/assets/1671260/8199541/0ba55978-147d-11e5-8e3c-a15a827f259b.png)

**Comment by krescruz** [comment]
Changed url that is sent by email. fd8102820fce09d6262e93fabe474016775db40

**Comment by lalongooo** [comment]
Thanks! Thanks! Thanks! :smile: :+1:
